### ISSUE TITLE
Can't get this to work with my C1! 

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/domoticz-cam-bridge#1]
To be honest I'm rather disappointed with this camera in general.. I have the bridge running and worked a while back with my old camera but this one doesn't seem to want to play ball. Maybe it won't work with this camera

<img width="1433" alt="screenshot 2017-01-22 10 21 31" src="https://cloud.githubusercontent.com/assets/15991296/22181855/3d2d3d66-e08d-11e6-9fb2-8d2fa5f838b0.png">

**Comment by PatchworkBoy** [comment]
Change server field to ftp:// instead of http://

**Comment by simonrb2000** [comment]
Thanks for your reply, I had already tried that, tried it again and still fails.

**Comment by PatchworkBoy** [comment]
Without protocol, just IP address?

**Comment by simonrb2000** [comment]
Fails still - trying to check the server is running correctly

**Comment by simonrb2000** [comment]
pi@raspberrypi:~$ sudo systemctl status domoticz-ftp-cam-bridge.service -l
● domoticz-ftp-cam-bridge.service - Domotic FTP Cam Bridge Service
   Loaded: loaded (/lib/systemd/system/domoticz-ftp-cam-bridge.service; enabled)
   Active: inactive (dead) since Sun 2017-01-22 08:44:58 GMT; 2h 49min ago
 Main PID: 1493 (code=exited, status=0/SUCCESS)

Jan 22 08:44:53 raspberrypi systemd[1]: Starting Domotic FTP Cam Bridge Service...
Jan 22 08:44:53 raspberrypi systemd[1]: Started Domotic FTP Cam Bridge Service.
Jan 22 08:44:58 raspberrypi forever[1493]: warn:    --minUptime not set. Defaulting to: 1000ms
Jan 22 08:44:58 raspberrypi forever[1493]: warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Jan 22 08:44:58 raspberrypi forever[1493]: info:    Forever processing file: /home/pi/domoticz-cam-bridge/server_ftp.js
pi@raspberrypi:~$

**Comment by simonrb2000** [comment]
Solved:- I put the address of the switch in the server_ftp.js file and its all working now!

Cheers
