### ISSUE TITLE
Camera will attempt to connect indefinitely 

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/domoticz-cam-bridge#3]
Hi,

I have been using this with my Foscams since you uploaded it. It’s been working flawlessly. 

I now have Reolink camera’s on the outside however FTP on those will constantly try to connect and won’t give up trying to connect, noticed this days later! Whoops

Is there a way to modify this to allow it to accept the connection so the camera will think it’s uploaded the file so it will disconnect? 

If not then I’ll think of another way... 

Many Thanks in advance

**Comment by PatchworkBoy** [comment]
Have looked over Reolink’s site - they don’t give a lot away as to what options you have nor how the current system works.

We’re spooling up a standard FTP server... if the camera isn’t working with it, then the camera’s implementation of FTP is wonked, or it’s expecting a specific response to something, or it’s using something more than plain-old-ftp (eg: ftps / tls etc).

You’d need to find a log of the ftp connection attempts on the camera and post that... or sniff the network session with Wireshark or summat...

**Comment by simonrb2000** [comment]
Firstly thank you for taking the time to research and respond. I shall take a look at this once I am home. 

I currently have a spare camera I could send if I can’t come up with anything?!?

Many Thanks

**Comment by PatchworkBoy** [comment]
Do a git pull, reset vars in server_ftp.js (note, specify ftpuser & ftppass, then use same values in camera client), start server_ftp.js, try it again... 

NB: uploads now work quite literally. This means you’re running an FTP server that allows full read/write access to the authenticated user. Authentication is in plain text / insecure, so only expose defined ports to trusted local networks. If you don’t actually want the uploads, knock up a cronjob to empty the folder’s contents regularly.

**Comment by simonrb2000** [comment]
That’s excellent thank you. I’m at the mother in laws, I shall try either tonight or tomorrow. 

Thanks again

**Comment by simonrb2000** [comment]
Had a chance to test this. It all works as expected! Thanks a million.

I just have to setup the 10 or so camera's up again lol.

I have noticed that I can leave the username and password out of the exiting Foscam camera's and they will still work as don't need the image saved. 

The Reolink camera's upload the file, and then disconnects so its working. Even when doing FTP test it comes up successful. Excellent!

Thanks again! Defo owe you a beer!
